// Set deterministic non-secret configuration before config.ts loads .env.
// dotenv does not overwrite these values. This is only imported by npm test.
Object.assign(process.env, {
  NODE_ENV: 'test',
  PORT: '3000',
  OSRM_BASE_URL: 'https://router.project-osrm.org',
  OSRM_TIMEOUT_MS: '12000',
  GEOCODING_SEARCH_RADIUS_KM: '20',
  DATABASE_URL: '',
  SERVICE_AREA_CENTER_LAT: '-8.4932',
  SERVICE_AREA_CENTER_LNG: '140.4018',
  SERVICE_AREA_RADIUS_KM: '50',
  MAX_DELIVERY_DISTANCE_KM: '50',
  RATE_LIMIT_WINDOW_MS: '60000',
  RATE_LIMIT_MAX_REQUESTS: '60',
  BASE_FARE: '15000',
  INCLUDED_KM: '2',
  PRICE_PER_KM: '3000',
  MINIMUM_FARE: '15000',
  FRONTEND_URL: 'http://localhost:5173',
  FRONTEND_URLS: 'http://localhost:5173',
  ADMIN_USERNAME: '',
  ADMIN_PASSWORD_HASH: '',
  ADMIN_SESSION_SECRET: '',
  WHATSAPP_NUMBER: '',
});
